//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVShowWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Episode
    {
        public string Id { get; set; }
        public string EpisodesTitle { get; set; }
        public string EpisodesDescriptions { get; set; }
        public string EpisodesAir { get; set; }
        public string EpisodesCover { get; set; }
        public string IdEpisode { get; set; }
    }
}
