//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVShowWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Rate { get; set; }
        public string Votes { get; set; }
        public string Poster { get; set; }
        public string Cat { get; set; }
        public string ActualSeasone { get; set; }
    }
}
