//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVShowWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torrent
    {
        public string IdShow { get; set; }
        public string IdEpisode { get; set; }
        public string Rozmiar { get; set; }
        public string Format { get; set; }
        public string Seed { get; set; }
        public string Peer { get; set; }
        public string Magnet { get; set; }
        public string Nazwa { get; set; }
    }
}
